### PR TITLE
Support hub images with a dash.

### PR DESCRIPTION
**Pull request by mcollina**
@Nss please review.

### CODE REVIEW

**Comment by Nss** [comment]
+1
The fix does its job, I'm not sure about removing the "-". I would have replaced them with some other character even a "_" to keep the separator.

**Comment by mcollina** [comment]
The problem with '_' is that it has a special meaning, as we use it to replace ':', which separate a tag from the image name in Docker. How about '.'?

**Comment by Nss** [comment]
I have limited knowledge of the system to judge this, you are probably the best to select the proper separator.

**Comment by mcollina** [comment]
Released as 0.16.7.

**Pull request merged**
