### PR TITLE
Removing some unused functions.

### PR DESCRIPTION
**Pull request by jsdevel**
This test has been failing for some time now (not sure why):
```
  kernel load test
    1) should load the kernel on a good config
```

### CODE REVIEW

**Comment by mcollina** [comment]
I know about the test, not sure what broke it in the past.
This is the last known build in which that test was working, if you want to get a look https://travis-ci.org/nearform/nscale-kernel/builds/61270395.

**Comment by mcollina** [comment]
(we were in a rush to ship some new features, and definitely mistepped something as the CI was broken anyway due to missing iojs 2.0 support)

**Comment by jsdevel** [comment]
I'll see if I can fix it.  Going through all the source code to complete the `do-droplet-container` assignment as we speak :smile:

**Comment by mcollina** [comment]
Great! If you have any questions just ping me.

**Pull request merged**
